/* File generated by ToTargetConfigFile.xsl */

#define XKCP_has_Sponge_Keccak
#define XKCP_has_FIPS202
#define XKCP_has_SP800_185
#define XKCP_has_Duplex_Keccak
#define XKCP_has_PRG_Keccak
#define XKCP_has_Ketje
#define XKCP_has_Keyak
#define XKCP_has_KangarooTwelve
#define XKCP_has_Kravatte
#define XKCP_has_Xoofff
#define XKCP_has_Xoodyak
#define XKCP_has_KeccakP1600
